## Thought Process

While we want to grant the user the power to drive their own analysis, one must create restrictions to the app to ensure that the provided distribution options, as well as parameterization ranges, make statistical and practical sense.

To model the total number socks, we choose priors that are both discrete and positive, hence the negative binomial distribution and normal distribution with  lower limit equal to zero. We create a dropdown menu where the user can choose between the two priors, and we create conditional slidebars that appear when the user makes their selection. For both priors, the mu and sigma slidebars range from (11, 1000) and (0, 100), respectively. The minimum value for mu is set to 11 because it is given information that 11 unique socks were pulled out of dryer—thus we know there are at least 11 socks. For the maximum, we select a large but reasonable number that would fit in an average-sized dryer. For sigma, we make the minimum zero and the maximum 100 to avoid over-dispersion. The default slider value of mu is 30, which reflects Rasmus' estimate (three people living in the house, changing their socks five times a week).

To model the proportion of pairs, the user may choose a beta prior or a normal prior truncated to [0,1]. We find beta a reasonable choice because it is flexible on the unit interval. We limit the distribution of the proportion to [0, 1] for mathematical sanity. We again create conditional slidebars; when the user selects beta, slidebars for alpha and beta appear, ranging from [.5, 100] so the user may construct an informative or noninfomative prior. The default values for alpha and beta are 15 and 2, respectively; this puts most of the mass in the model between .75 and 1.0 (a reasonable estimate for the proportion of pairs). We include the normal prior truncated on interval [0,1] because it also restricts the distribution to the [0,1] range. The default slider value of mu is .75, because it is typical for there to be singletons, and the slider ranges [0,1], again for mathematical sanity.

For visual purposes, we choose a numeric input textbox (as opposed to a slidebar) where the user may enter the number of simulations, in order to avoid an overextended slidebar.

In order to implement Rasmus' model in an efficient manner, we must alter his code. Most importantly, we turn the replication loop in his code into an auxillary sampling function, which acts as our generative model. We are able to use this sampling function inside an `lapply` function, which allows us to carry out the prior sampling. 
